---
# tasks file for win_ad_install
- name: 1.0 | Install Active Directory
  win_feature:
    name: AD-Domain-Services
    state: present

- name: 2.0 | Configure Active Directory
  win_domain:
    dns_domain_name: "{{ hostvars[groups['windows'][0]].ansible_host }}"
    safe_mode_password: "{{ ansible_password }}"
  register: ad_controllers

- name: 3.0 | Reboot the server
  win_reboot:
  when: ad_controllers.reboot_required
