---
- name: 1.0 | General Configuration
  hosts: all
  become: true
  tasks:
  - name: Include Common role
    include_role:
      name: lmaly.common
  tags:
    - general

- name: 2.0 | Apply HAproxy role
  hosts: frontends
  become: true
  tasks:
  - name: Include HAproxy role
    include_role:
      name: lmaly.haproxy
  tags:
    - haproxy
    - frontend

- name: 3.0 | Apply Tomcat role
  hosts: apps
  gather_facts: false
  become: true
  tasks:
  - name: Include Tomcat role
    include_role:
      name: lmaly.tomcat
  tags:
    - tomcat
    - app

- name: 4.0 | Apply PostgreSQL role
  hosts: appdbs
  become: true
  tasks:
  - name: Include PostgreSQL role
    include_role:
      name: lmaly.postgres
  tags:
    - postgresql
    - db

- name: 5.0 | Smoke test
  hosts: frontends
  tasks:
  - name: Include smoke test
    include_tasks: tests/main.yml
  tags:
    - tests
