---
- name: 1.0 | General Configuration
  hosts: all
  become: true
  tasks:
  - name: Include Common role
    include_role:
      name: lmaly.common

- name: 2.0 | Apply HAproxy role
  hosts: frontends
  become: true
  tasks:
  - name: Include HAproxy role
    include_role:
      name: lmaly.haproxy

- name: 3.0 | Apply Tomcat role
  hosts: apps
  gather_facts: false
  become: true
  tasks:
  - name: Include Tomcat role
    include_role:
      name: lmaly.tomcat

- name: 4.0 | Apply PostgreSQL role
  hosts: appdbs
  gather_facts: false
  become: true
  tasks:
  - name: Include Postgres role
    include_role:
      name: lmaly.postgres
