---
# tasks file for win_domain_user
# tasks file for roles/win_ad_user
- name: 1.0 | Create domain group
  win_domain_group:
    name: "{{ item.group_name }}"
    scope: "{{ item.group_scope }}"
    state: present
  loop: "{{ user_info }}"

- name: 2.0 | Create AD user
  win_domain_user:
    name: "{{ item.name }}"
    firstname: "{{item.firstname }}"
    surname: "{{ item.surname }}"
    password: "{{ item.password }}"
    groups: "{{ item.group_name }}"
    state: present
    email: "{{ item.name }}@{{ hostvars[groups['windows'][0]].ansible_host }}"
  loop: "{{ user_info }}"
